source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-assetpack', :require => 'sinatra/assetpack'
gem 'sinatra-contrib'
gem 'rerun'
gem 'unicorn'
gem 'compass'
gem 'osdb'
gem 'rspec', '~> 2.14.1'
gem 'json'
